services:
  # Backend API
  - type: web
    name: exchangepmr-api
    env: node
    plan: free
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: CLIENT_URL
        value: https://exchangepmr-web.onrender.com
    healthCheckPath: /health
    
  # Frontend Web App  
  - type: web
    name: exchangepmr-web
    env: static
    plan: free
    buildCommand: cd apps/web && npm install && npm run build
    staticPublishPath: apps/web/dist
    envVars:
      - key: VITE_API_URL
        value: https://exchangepmr-api.onrender.com/api
      - key: VITE_WS_URL
        value: wss://exchangepmr-api.onrender.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOW-FROM https://telegram.org/
    routes:
      - type: rewrite
        source: /*
        destination: /index.html